services:
  voxfox:
    image: voxfox-webapi
    container_name: voxfox-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8081"
      - "9090:9091"
    environment:
      - Ports__Api=8081
      - Ports__Metrics=9091
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=voxfox_db;Username=postgres;Password=password
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=voxfox_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command:
      - "postgres"
      - "-c"
      - "shared_preload_libraries=uuid-ossp"
    ports:
      - "5436:5432"
    volumes:
      - voxfox_postgres_data:/var/lib/postgresql/data

volumes:
  voxfox_postgres_data:
