name: Commitlint

on:
  pull_request:
    branches:
      - master
      - staging
      - dev

jobs:
  commitlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install commitlint
        run: |
          npm install -g @commitlint/cli @commitlint/config-conventional

      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: ./commitlint.config.mjs
          token: ${{ secrets.GITHUB_TOKEN }}
