name: Build and Push to ECR (STAGING)

env:
  AWS_REGION: eu-north-1
  AWS_IAM_ROLE: arn:aws:iam::703671934401:role/github-actions
  ECR_REPOSITORY: lisatrishchenkova/voxfox-practice-backend

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [staging]

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-24.04
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_IAM_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate staging tag
        id: tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          DATE=$(date -u +'%Y%m%d-%H%M')
          IMAGE_TAG="staging-${DATE}-${SHORT_SHA}"

          echo "tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
          echo "build_date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Build and push STAGING image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.tag.outputs.tag }}
        run: |
          docker buildx create --use --name builder
          docker buildx inspect builder --bootstrap

          docker buildx build \
            --target staging \
            --build-arg APP_VERSION=${{ steps.tag.outputs.tag }} \
            --build-arg GIT_COMMIT=${{ steps.tag.outputs.short_sha }} \
            --build-arg BUILD_DATE=${{ steps.tag.outputs.build_date }} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:staging-latest \
            --load \
            -f Dockerfile .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:staging-latest

          docker buildx rm builder

      - name: Summary
        if: always()
        run: |
          echo "### 📦 Staging image pushed" >> $GITHUB_STEP_SUMMARY
          echo "**Tag:** ${{ steps.tag.outputs.tag }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ steps.tag.outputs.short_sha }}" >> $GITHUB_STEP_SUMMARY
