name: Deploy Backend To Server Home

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: env-server-home
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --target staging -t voxfox-api:latest .

      - name: Save & upload image
        run: docker save voxfox-api:latest | gzip > image.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "image.tar.gz"
          target: "/opt/voxfox"

      - name: Run on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/voxfox
            docker load < image.tar.gz
            docker stop voxfox-api || true
            docker rm voxfox-api || true
            docker run -d \
              --name voxfox-api \
              --restart unless-stopped \
              -p 127.0.0.1:8000:8000 \
              --env-file .env \
              voxfox-api:latest
            rm image.tar.gz